version: '3.1'

services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - "/home/mateus/docker-volumes/postgres-dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=nestdb
      - POSTGRES_DB=nestdb